version: "3"

services:
  #reverse build
  reverse:
    build: .
    image: cs56022218/dailyfix-reverse:latest
    container_name: dailyfix-reverse
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      # - ./nginx:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html


